// Auto-generated ABI for Lottery.sol
export const LOTTERY_ABI = [
  {"type":"function","name":"announceWinner","inputs":[{"name":"lotteryId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"buyTickets","inputs":[{"name":"lotteryId","type":"uint256","internalType":"uint256"},{"name":"quantity","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"payable"},
  {"type":"function","name":"createLottery","inputs":[{"name":"title","type":"string","internalType":"string"},{"name":"description","type":"string","internalType":"string"},{"name":"ticketPrice","type":"uint256","internalType":"uint256"},{"name":"totalTickets","type":"uint256","internalType":"uint256"},{"name":"endTime","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"getPlayers","inputs":[{"name":"lotteryId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"address[]","internalType":"address[]"}],"stateMutability":"view"},
  {"type":"function","name":"lotteries","inputs":[{"name":"","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"creator","type":"address","internalType":"address"},{"name":"title","type":"string","internalType":"string"},{"name":"description","type":"string","internalType":"string"},{"name":"ticketPrice","type":"uint256","internalType":"uint256"},{"name":"totalTickets","type":"uint256","internalType":"uint256"},{"name":"soldTickets","type":"uint256","internalType":"uint256"},{"name":"endTime","type":"uint256","internalType":"uint256"},{"name":"winner","type":"address","internalType":"address"},{"name":"isActive","type":"bool","internalType":"bool"},{"name":"winnerAnnounced","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"nextLotteryId","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"event","name":"LotteryCreated","inputs":[{"name":"lotteryId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"creator","type":"address","indexed":true,"internalType":"address"},{"name":"title","type":"string","indexed":false,"internalType":"string"},{"name":"ticketPrice","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"totalTickets","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"endTime","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"event","name":"TicketPurchased","inputs":[{"name":"lotteryId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"buyer","type":"address","indexed":true,"internalType":"address"},{"name":"quantity","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"event","name":"WinnerAnnounced","inputs":[{"name":"lotteryId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"winner","type":"address","indexed":true,"internalType":"address"}],"anonymous":false}
];
