export const LOTTERY_ABI = [
    {
      type: "constructor",
      inputs: [
        { name: "_campfireNFT", type: "address", internalType: "address" },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "MAX_LOTTERY_DURATION",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "MIN_LOTTERY_DURATION",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "buyTicket",
      inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "campfireNFT",
      inputs: [],
      outputs: [
        { name: "", type: "address", internalType: "contract IERC721" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "canDrawLottery",
      inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "cancelLottery",
      inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "drawLottery",
      inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "emergencyWithdraw",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "getAllActiveLotteries",
      inputs: [],
      outputs: [
        {
          name: "",
          type: "tuple[]",
          internalType: "struct CoreCampLottery.Lottery[]",
          components: [
            { name: "tokenId", type: "uint256", internalType: "uint256" },
            { name: "owner", type: "address", internalType: "address" },
            { name: "ticketPrice", type: "uint256", internalType: "uint256" },
            { name: "maxTickets", type: "uint256", internalType: "uint256" },
            { name: "isActive", type: "bool", internalType: "bool" },
            { name: "players", type: "address[]", internalType: "address[]" },
            { name: "createdAt", type: "uint256", internalType: "uint256" },
            { name: "endTime", type: "uint256", internalType: "uint256" },
            { name: "winner", type: "address", internalType: "address" },
            { name: "isDrawn", type: "bool", internalType: "bool" },
          ],
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getAllLotteryTokenIds",
      inputs: [],
      outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getCurrentLotteryId",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getLottery",
      inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
      outputs: [
        { name: "lotteryTokenId", type: "uint256", internalType: "uint256" },
        { name: "owner", type: "address", internalType: "address" },
        { name: "ticketPrice", type: "uint256", internalType: "uint256" },
        { name: "maxTickets", type: "uint256", internalType: "uint256" },
        { name: "isActive", type: "bool", internalType: "bool" },
        { name: "ticketsSold", type: "uint256", internalType: "uint256" },
        { name: "endTime", type: "uint256", internalType: "uint256" },
        { name: "winner", type: "address", internalType: "address" },
        { name: "isDrawn", type: "bool", internalType: "bool" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getLotteryStatus",
      inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
      outputs: [
        { name: "exists", type: "bool", internalType: "bool" },
        { name: "isActive", type: "bool", internalType: "bool" },
        { name: "hasEnded", type: "bool", internalType: "bool" },
        { name: "isSoldOut", type: "bool", internalType: "bool" },
        { name: "currentTime", type: "uint256", internalType: "uint256" },
        { name: "endTime", type: "uint256", internalType: "uint256" },
        { name: "ticketsSold", type: "uint256", internalType: "uint256" },
        { name: "maxTickets", type: "uint256", internalType: "uint256" },
        { name: "owner", type: "address", internalType: "address" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getPlayers",
      inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "lotteries",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [
        { name: "tokenId", type: "uint256", internalType: "uint256" },
        { name: "owner", type: "address", internalType: "address" },
        { name: "ticketPrice", type: "uint256", internalType: "uint256" },
        { name: "maxTickets", type: "uint256", internalType: "uint256" },
        { name: "isActive", type: "bool", internalType: "bool" },
        { name: "createdAt", type: "uint256", internalType: "uint256" },
        { name: "endTime", type: "uint256", internalType: "uint256" },
        { name: "winner", type: "address", internalType: "address" },
        { name: "isDrawn", type: "bool", internalType: "bool" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "lotteryExists",
      inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "lotteryTokenIds",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "owner",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "platformFeeBps",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "renounceOwnership",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "startLottery",
      inputs: [
        { name: "tokenId", type: "uint256", internalType: "uint256" },
        { name: "ticketPrice", type: "uint256", internalType: "uint256" },
        { name: "maxTickets", type: "uint256", internalType: "uint256" },
        { name: "duration", type: "uint256", internalType: "uint256" },
      ],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "tokenToLotteryId",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "transferOwnership",
      inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "updatePlatformFee",
      inputs: [{ name: "newFeeBps", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "event",
      name: "LotteryCancelled",
      inputs: [
        {
          name: "lotteryId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "owner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "LotteryCreated",
      inputs: [
        {
          name: "lotteryId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "tokenId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "owner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "ticketPrice",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "maxTickets",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "endTime",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "LotteryDrawCompleted",
      inputs: [
        {
          name: "lotteryId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "winner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "randomWord",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          name: "previousOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "newOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "PrizeDistributed",
      inputs: [
        {
          name: "lotteryId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "winner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "owner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "prizeAmount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "TicketPurchased",
      inputs: [
        {
          name: "lotteryId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "buyer",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "ticketNumber",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
  ]
  